name: CI

on: [pull_request]

jobs:
  test_suite:
    name: Test Suite
    runs-on: ubuntu-latest
    env:
      GITHUB_API_TOKEN: foo
    strategy:
      matrix:
        ruby-version: [head, 4.0, 3.4, 3.3, 3.2]
      fail-fast: false
    continue-on-error: ${{ endsWith(matrix['ruby-version'], 'head') }}
    steps:
    - uses: actions/checkout@v6
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rspec
  sorbet:
    name: Sorbet typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: ${{ env.REPO_FETCH_DEPTH }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Sorbet
        run: bundle exec srb typecheck
  # Ruby summary job, for branch protection rules
  # Head ruby failures are ignored due to continue-on-error in the test job.
  all-tests:
    name: Ruby (non-head) tests passed
    runs-on: ubuntu-latest
    needs: [test_suite]
    if: always()
    steps:
      - name: Check test suite results
        run: |
          [[ "${{ needs.test_suite.result }}" == "success" ]] || exit 1
